### ISSUE TITLE
Add option to mark colors as `primary`, `secondary`, etc

### ISSUE THREAD

**Issue by Luckey-Elijah** [Luckey-Elijah/gator#14]
I want to mark a color with an alias

```yaml
gator:
  class: ExampleColors
  output: lib/src/colors.g.dart
  colors:
    Pale Spring Bud: 
      hex: 'dce2aa'
      alias: primary
```
```dart
  /// Primary App Color:
  /// **Pale Spring Bud**
  static const MaterialColor primary = paleSpringBud;

  static const _paleSpringBudPrimaryValue = 0xffdce2aa;

  /// **Pale Spring Bud**
  /// {@macro gator_header}
  static const paleSpringBud = MaterialColor(
    _paleSpringBudPrimaryValue,
    <int, Color>{
      050: Color(0xffeaeecc),
      100: Color(0xffe7ebc4),
      200: Color(0xffe3e8bb),
      300: Color(0xffe0e5b3),
      400: Color(0xffdce2aa),
      500: Color(_paleSpringBudPrimaryValue),
      600: Color(0xffc6cb99),
      700: Color(0xffb0b588),
      800: Color(0xff9a9e77),
      900: Color(0xff848866),
    },
  );
```
