### ISSUE TITLE
Feat: Add output to configuration

### ISSUE THREAD

**Issue by Luckey-Elijah** [Luckey-Elijah/gator#5]
As a developer I want to specify the output of the generated file in the configuration. So

```sh
gator -c colors.yaml -o example/my_colors.dart
```

Turns into

```yaml
gator:
  output: example/my_colors.dart
  class: MyColors
  colors:
    royalBlue: '0xff062091'
    grey: '#d6d6d6'
    rebeccaPurple: '663399'
```
